{"name": "Ошибка при авторизации с неверным логином", "status": "passed", "start": 1719934905903, "stop": 1719934906384, "uuid": "e43a5d54-20ce-47b4-9a24-f8fb60f7f301", "historyId": "36c490236660942a89313446ee570a2f", "testCaseId": "36c490236660942a89313446ee570a2f", "fullName": "tests.test_login.TestLogin#test_login_bad_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "MacBook-Pro-Ula.local"}, {"name": "thread", "value": "8866-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}